FROM node:5.10-slim
RUN \
  apt-get update \
  && apt-get install -y git \
  && npm install markdown-to-slides@1.0.3 --global \
  && npm cache clean \
  && apt-get remove --purge -y git \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/*
WORKDIR /var/www
COPY . .
VOLUME /var/www
ENTRYPOINT ["markdown-to-slides", "slides.md", "--include-remark"]
