FROM node:5.9-slim
ENV MARKDOWN_TO_SLIDES_VERSION 1.0.2
RUN npm install markdown-to-slides@$MARKDOWN_TO_SLIDES_VERSION --global
WORKDIR /var/www
COPY . .
VOLUME /var/www
ENTRYPOINT ["markdown-to-slides", "slides.md"]
