#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset
trap 'echo "$0: line $LINENO: exit status of last command: $?" 1>&2' ERR

slides_port=8080

command-exists() {
  command -v "$1" >/dev/null 2>&1
}

# Note that this assumes you're using the default machine name for
# docker-machine.
if command-exists docker-machine && [ $(docker-machine status) = "Running" ]
then
  docker_host=$(docker-machine ip)
else
  docker_host="localhost"
fi
slides_url="http://$docker_host:$slides_port"

echo
echo "Opening $slides_url..."
if command-exists xdg-open
then
  xdg-open "$slides_url"
elif command-exists open
then
  open "$slides_url"
else
  echo "Couldn't figure out how to open $slides_url" 1>&2
fi
