#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset
trap 'echo "$0: line $LINENO: exit status of last command: $?" 1>&2' ERR

slides_port=8080

command-exists() {
  command -v "$1" >/dev/null 2>&1
}

get-docker-host() {
  # Note that this assumes you're using the default machine name for
  # docker-machine.
  if command-exists docker-machine && [ $(docker-machine status) = "Running" ]
  then
    docker-machine ip
  else
    echo "localhost"
  fi
}

generic-open() {
  if command-exists xdg-open
  then
    xdg-open "$1"
  elif command-exists open
  then
    open "$1"
  else
    echo "Couldn't figure out how to open $1" 1>&2
  fi
}

slides_url="http://$(get-docker-host):$slides_port"

echo
echo "Opening $slides_url..."
generic-open $slides_url
